
CREATE TABLE one_another_groups (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    group_access TEXT NOT NULL,
    group_name TEXT NOT NULL UNIQUE,
    pitch TEXT,
    group_leader INTEGER REFERENCES one_another_users(id) ON DELETE CASCADE,
    leader_phone TEXT NOT NULL,
    group_location TEXT NOT NULL,
    time_date TEXT NOT NULL,
    more_info TEXT,
    user_ids TEXT[],
    pending_users TEXT[],
    group_pic TEXT,
    UNIQUE (id)
);