CREATE TABLE needed_items (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	event_id int4 NULL,
	user_id int4 NULL,
	item_name text NOT NULL,
	CONSTRAINT needed_items_pkey PRIMARY KEY (id),
	CONSTRAINT needed_items_event_id_fkey FOREIGN KEY (event_id) REFERENCES create_event(id) ON DELETE CASCADE,
	CONSTRAINT needed_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES one_another_users(id)
);