CREATE TABLE messages (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  message_time TIMESTAMPTZ DEFAULT now() NOT NULL,
  message_type TEXT NOT NULL,
  message_body TEXT NOT NULL,
  message_like BOOLEAN,
  message_likes INTEGER,
  group_chat INTEGER REFERENCES one_another_groups(id)ON DELETE CASCADE,
  user_id INTEGER REFERENCES one_another_users(id)ON DELETE CASCADE
);