CREATE TABLE prayers (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  prayer_time TIMESTAMPTZ DEFAULT now() NOT NULL,
  prayer_type TEXT NOT NULL,
  prayer_body TEXT NOT NULL,
  prayer_like BOOLEAN,
  prayer_likes INTEGER,
  group_prayer INTEGER REFERENCES one_another_groups(id)ON DELETE CASCADE,
  user_id INTEGER REFERENCES one_another_users(id)ON DELETE CASCADE
);